use_frameworks!

platform :ios, '10.0'

target 'unif-search_Example' do
  pod 'unif-search', :path => '../'

  target 'unif-search_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
